import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
    "./node_modules/@shadcn/ui/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontSize: {

        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-mono': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
      },
      spacing: {

        'margin-desktop': '64px',
        gutter: '24px',
        'max-width': '1280px',
        'margin-mobile': '16px',
        unit: '4px',
      },
      colors: {

        'on-primary': '#ffffff',
        'surface-variant': '#d3e4fe',
        'primary-fixed-dim': '#67d9c9',
        'on-primary-fixed': '#00201c',
        'inverse-primary': '#67d9c9',
        'on-background': '#0b1c30',
        'surface-tint': '#006a60',
        'on-surface': '#0b1c30',
        'surface-container-low': '#eff4ff',
        'outline-variant': '#bcc9c6',
        'error-container': '#ffdad6',
        'on-primary-fixed-variant': '#005048',
        'on-secondary-fixed': '#001a41',
        'surface': '#f8f9ff',
        'tertiary-fixed-dim': '#b5c8e5',
        'on-error-container': '#93000a',
        'primary-container': '#008377',
        'secondary-fixed-dim': '#adc7ff',
        'tertiary-container': '#637690',
        'on-primary-container': '#f4fffb',
        'secondary-fixed': '#d8e2ff',
        'on-secondary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-fixed': '#081c32',
        'on-surface-variant': '#3d4947',
        'surface-container': '#e5eeff',
        'on-tertiary-container': '#fdfcff',
        'inverse-surface': '#213145',
        'secondary-container': '#0070ea',
        'error': '#ba1a1a',
        'tertiary': '#4b5d76',
        'outline': '#6d7a77',
        'surface-container-highest': '#d3e4fe',
        'on-tertiary': '#ffffff',
        'on-secondary-fixed-variant': '#004493',
        'on-tertiary-fixed-variant': '#364860',
        'inverse-on-surface': '#eaf1ff',
        'surface-dim': '#cbdbf5',
        'surface-container-high': '#dce9ff',
        'tertiary-fixed': '#d2e4ff',
        'on-error': '#ffffff',
        'on-secondary-container': '#fefcff',
        'primary-fixed': '#85f6e5',
        'surface-bright': '#f8f9ff',

        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: "hsl(var(--card))",
        "card-foreground": "hsl(var(--card-foreground))",
        popover: "hsl(var(--popover))",
        "popover-foreground": "hsl(var(--popover-foreground))",
        primary: "hsl(var(--primary))",
        "primary-foreground": "hsl(var(--primary-foreground))",
        secondary: "hsl(var(--secondary))",
        "secondary-foreground": "hsl(var(--secondary-foreground))",
        muted: "hsl(var(--muted))",
        "muted-foreground": "hsl(var(--muted-foreground))",
        accent: "hsl(var(--accent))",
        "accent-foreground": "hsl(var(--accent-foreground))",
        destructive: "hsl(var(--destructive))",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        // Chart Colors
        "chart-1": "hsl(var(--chart-1))",
        "chart-2": "hsl(var(--chart-2))",
        "chart-3": "hsl(var(--chart-3))",
        "chart-4": "hsl(var(--chart-4))",
        "chart-5": "hsl(var(--chart-5))",
        // Sidebar Colors
        sidebar: "hsl(var(--sidebar))",
        "sidebar-foreground": "hsl(var(--sidebar-foreground))",
        "sidebar-primary": "hsl(var(--sidebar-primary))",
        "sidebar-primary-foreground": "hsl(var(--sidebar-primary-foreground))",
        "sidebar-accent": "hsl(var(--sidebar-accent))",
        "sidebar-accent-foreground": "hsl(var(--sidebar-accent-foreground))",
        "sidebar-border": "hsl(var(--sidebar-border))",
        "sidebar-ring": "hsl(var(--sidebar-ring))",
      },
      borderRadius: {
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
      },
      fontFamily: {

        'display-lg': ['Work Sans', 'sans-serif'],
        'headline-lg': ['Work Sans', 'sans-serif'],
        'headline-md': ['Work Sans', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Work Sans', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-mono': ['JetBrains Mono', 'monospace'],

        sans: "var(--font-sans)",
        mono: "var(--font-mono)",
      },
      screens: {
        "3xl": "1650px",
      },
    },
  },
  plugins: [],
};

export default config;